RobotLocomotion/drake-ros

drake_ros_core/src/ros_subscriber_system.cpp
After building with Drake's nightly binaries on Focal 20.04 on `rolling`, I encountered a few Drake API deprecation warnings. These updates fix the warnings. I'll have a Docker build and CI working shortly to make these warnings more obvious as they happen  in realtime.
Together with #12 this will resolve #10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/11)
=> Fix Drake deprecation warnings

drake_ros_core/src/subscription.hpp
Closes #14. Use `virtual` keyword instead of `override` keyword.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/17)
=> Fix Subscription class in Galactic

drake_ros_core/.clang-format, drake_ros_core/CMakeLists.txt, drake_ros_core/CPPLINT.cfg, drake_ros_core/include/drake_ros_core/drake_ros.hpp, drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp, drake_ros_core/include/drake_ros_core/ros_interface_system.hpp, drake_ros_core/include/drake_ros_core/ros_publisher_system.hpp, drake_ros_core/include/drake_ros_core/ros_subscriber_system.hpp, drake_ros_core/include/drake_ros_core/serializer.hpp, drake_ros_core/include/drake_ros_core/serializer_interface.hpp, drake_ros_core/package.xml, drake_ros_core/src/drake_ros.cpp, drake_ros_core/src/publisher.cpp, drake_ros_core/src/publisher.hpp, drake_ros_core/src/ros_interface_system.cpp, drake_ros_core/src/ros_publisher_system.cpp, drake_ros_core/src/ros_subscriber_system.cpp, drake_ros_core/src/subscription.cpp, drake_ros_core/src/subscription.hpp, drake_ros_core/test/test_drake_ros.cpp, drake_ros_core/test/test_pub_sub.cpp
Closes #15. Precisely what the title says. This patch configures `ament_cpplint` and `ament_clang_format` linters to match [drake](https://github.com/RobotLocomotion/drake)'s style (pulling in their configuration).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/16)
=> Configure linters to comply with Drake C++ style

tools/containers/drake_ros_core.Dockerfile
This seems to work fine without it when building locally
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/18)
=> Don't install test messages in CI dockerfile

bazel_ros2_rules/ros2/resources/templates/package_cc_library.bazel.tpl, bazel_ros2_rules/ros2/resources/templates/setup.sh.in, bazel_ros2_rules/ros2/ros2bzl/scraping/ament_cmake.py, ros2_example_bazel_installed/README.md, ros2_example_bazel_installed/WORKSPACE, ros2_example_bazel_installed/setup/install_prereqs.sh
Precisely what the title says. This patch ensures we use Rolling on Focal tarballs instead of plain Rolling debians (soon to transition to Jammy). 
Two changes and a bugfix went into `bazel_ros2_rules` to get things working. Namely:
- Constrain header files to `.h*` files in `cc_library` template invocations
- Set `$COLCON_CURRENT_PREFIX` before sourcing workspaces
- Fix an omission in `ament_cmake` package scraping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/37)
=> Use Rolling on Focal via tarball installed via prereqs

bazel_ros2_rules/ros2/defs.bzl
Precisely what the title says. Useful to implement other ROS 2 repository rules downstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/45)
=> Expose `bazel_ros2_rules` ros2 repository logic.

drake_ros_core/test/test_pub_sub.py
It can take some time for an asynchronous DDS implementation to initialize and connect with existing subscribers. Before beginning the round trip test, we should make sure that the ROS publisher has successfully connected to the subscriber.
This should resolve the test failure when using Fast-DSS, which is the new default RMW implementation for ROS 2 Humble. Without waiting, the first message being published from ROS seems to be lost, meaning the first message recieved from Drake is a '0', which fails the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/47)
=> Wait for subscription to begin testing

drake_ros_core/CPPLINT.cfg
The name of the rule which tracks this behavior has changed in the version of cpplint used in Humble. Unfortunately, there doesn't seem to be a single suppression that works with both Galactic and Humble cpplint.
This filter should unblock builds in Humble, while the existing suppressions mentioned in the comment should continue to work for Galactic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/48)
=> Add suppression for cpplint in Humble

bazel_ros2_rules/ros2/compute_system_rosdeps.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/50)
=> Ignore iceoryx_binding_c rosdep key

.github/workflows/main.yml
This fixes CI
`iceoryx_binding_c` needs to be skipped for reasons explained in #50.
When installing from the archive, only the `exec`, `buildtool_export`, and `build_export` dependencies are needed. Specifying that removes an error message about some non-existance build only dependencies.
The github workflow somewhat duplicates the knowledge in `bazel_ros2_rules/ros2/compute_system_rosdeps.py`. Maybe a future enhancement could use that script in CI?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/52)
=> Only install exec, buildtool_export, and build_export deps plus skip iceoryx_binding_c

.github/workflows/main.yml, bazel_ros2_rules/ros2/compute_system_rosdeps.py
This should fix drake-ros CI. I think it was broken by ros2/rosidl_defaults/pull/20 - see this comment for more info https://github.com/ros2/rosidl_defaults/issues/21#issuecomment-1089139080
@IanTheEngineer & @EricCousineau-TRI FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/56)
=> Skip Fast-DDS typesupport keys

ros2_example_bazel_installed/setup/install_prereqs.sh
This calls `rosdep update` automatically if it hasn't been already, which is the default state after running `ros2_example_bazel_installed/setup/install_prereqs.sh` assuming the user has never used `rosdep` before.
We can't just add `rosdep update` to `install_prereqs.sh` because `rosdep update` must be run as the non-root user.
To test what happens if the rosdep database has been initialized but not updated, delete the rosdep cache in the home directory.
```console
$ rm -rf ~/.ros/rosdep
```
To test what happens if the rosdep database has never been initialized, delete both of these folders:
```console
$ rm -rf /etc/ros/rosdep/
$ rm -rf ~/.ros/rosdep
```
@IanTheEngineer & @EricCousineau-TRI  FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Call rosdep update in install_prereqs.sh

drake_ros_tf2/src/utilities/name_conventions.cc, drake_ros_tf2/test/test_name_conventions.cc
This PR makes the TF frame for the world frame always be `world`. Currently the frame ends up being `WorldModelInstance/WorldBody/10`. It's not obvious to me if the ` drake::geometry::FrameId` at the end is stable. If not, it would be hard to make an RViz config.
It must have evaluated to `world` at some point in the past because the example PR uses a fixed frame of `world` already in its RViz config.
https://github.com/RobotLocomotion/drake-ros/blob/28b4920e67715eab25fe425601e8fe4529e28a69/drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.rviz#L91
@IanTheEngineer & @EricCousineau-TRI thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/57)
=> Make TF frame name for world frame always be world

bazel_ros2_rules/ros2/ros2bzl/scraping/system.py, bazel_ros2_rules/ros2/ros2bzl/templates.py
Fixes #60
~~I don't understand the problem completely, so I'm not 100% sure this is the right fix.~~
The amdgpu driver adds a file to `/etc/ld.so.conf.d/` to specify a directory in `/opt` that should be searched by the dynamic loader when resolving a shared library's dynamic dependencies (stuff output when doing `ldd libsomelibrary.so`).~~
The CMake scraping code looks at libraries that need to be linked with a given target. Sometimes it knows it needs to link with a system shared library, and somehow it determines that library can be found in one of the folders `/etc/ld.so.conf.d`. This gets reported to code populating the templates for `BUILD.bazel`. That code tries to map the found library to a path in the sandbox, but it can't, so it leaves it as an absolute path to the library. The …
=> Determine system library dirs by asking ld and ldconfig 

bazel_ros2_rules/ros2/ros2bzl/scraping/system.py
Cherry-pick from #59 
Alternative to #65 
This resolves the issue with libraries in `/.singularity.d/libs` being included in the ros2 `BUILD.bazel` file similar to #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/69)
=> Be explicit about Apptainer/Singularity workaround

.github/workflows/main.yml
We can and should continue to use http to download the CI archive if we verify the integrity using the corresponding checksum file, which we can download securely.
This adds both authenticity (via https certificate) and integrity (via sha256sum) checking for downloading the archive for CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/70)
=> Use https to download and verify CI archive checksum

drake_ros_viz/test/test_python_bindings.py
#24 added tests to the Python bindings for visualisation, but unfortunately a debug print was left in by mistake. This PR removes the print.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/81)
=> Remove unnecessary print from test

bazel_ros2_rules/ros2/resources/rmw_isolation/package.BUILD.bazel
This makes the `rmw_isolation_py` target visible so it can be used in downstream projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/87)
=> Make rmw_isolation_py visible

drake_ros_examples/package.xml
Need this PR to build `drake_ros_examples` with Colcon: https://gist.github.com/sloretz/074541edfe098c56ff42836118d94a8d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/88)
=> Add missing test dependency on ament_cmake_clang_format

.github/workflows/main.yml, drake_ros_core/WORKSPACE, ros2_example_bazel_installed/WORKSPACE
The Rolling distribution changes quickly, and now that it has been released, the Humble LTS is a much more stable target that contains all of the features we need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/89)
=> Switch from Rolling-based underlay to Humble

bazel_ros2_rules/ros2/resources/ros2bzl/scraping/metadata.py
The current scrapping code assumes pluginlib description files are always called `plugins_description.xml`, however that's not always true. The `image_transport` package doesn't name it's plugin description this way, and that prevents loading the `Image` display plugin in RViz when using `bazel run @ros2//:rviz2`.
This fixes it by looking up the plugins provided by a package in the ament resource index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/92)
=> Fix scraping of plugin libraries from the ament index

bazel_ros2_rules/ros2/defs.bzl, bazel_ros2_rules/ros2/generate_distro_file.py, bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl, bazel_ros2_rules/ros2/tools/dload.bzl, bazel_ros2_rules/ros2/tools/dload_cc.bzl, bazel_ros2_rules/ros2/tools/dload_py.bzl
This adds an option to `bazel_ros2_rules` that allows configuring whether `RMW_LOCALHOST_ONLY` is set to 0 or 1 by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/94)
=> Add option to set RMW_LOCALHOST_ONLY by default

bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py, ros2_example_bazel_installed/WORKSPACE
Fixes #100
Here's what it looks like with a non-existent package
```
bazel build //...
INFO: Repository ros2 instantiated at:
/home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:34:13: in <toplevel>
Repository rule ros2_archive defined at:
/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
* Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the definition of 'ros2' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of …
```
=> Error when requested package doesn't exist in ROS 2 workspace

bazel_ros2_rules/ros2/ros_cc.bzl, bazel_ros2_rules/ros2/ros_py.bzl
This renames the not-shimmed binaries from `_*_shimmed` to `_*_noshim`. This is something @EricCousineau-TRI suggested when he was helping me with questions about this code last week.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/112)
=> Rename not-shimmed executables

bazel_ros2_rules/WORKSPACE, bazel_ros2_rules/ros2/defs.bzl, bazel_ros2_rules/ros2/ros_cc.bzl, bazel_ros2_rules/ros2/rosidl.bzl, bazel_ros2_rules/ros2/tools/ament_index.bzl, bazel_ros2_rules/ros2/tools/dload.bzl, ros2_example_bazel_installed/WORKSPACE, ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel, ros2_example_bazel_installed/ros2_example_apps/test/custom_message_echo_test.py, ros2_example_bazel_installed/ros2_example_apps/test/custom_message_list_test.py
Fixes #118 
Contains #120
This creates an ament resource index describing the existence of custom messages created with `rosidl_interfaces_group()`. The index is made available as runfiles to any target that depends on `{group name}_ament_index`. The dload shim uses a bazel aspect to accumulate declared ament index prefixes, and prepends `AMENT_PREFIX_PATH` with them.
Note that the `ros2 interface list` test in `custom_message_echo_test` now passes because it depends on `:ros2_example_apps_msgs_ament_index`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)
=> Create ament index for custom messages and make dload shims aware of it

bazel_ros2_rules/ros2/generate_build_file.py
Python sets do not maintain any order information. Iterating over them may yield different orders among attempts.
The intermediate fallout from the nondeterministic processing of dependencies is that the include directory arguments passed to compiler invocations is related in some way to the order in which the dependencies are processed. This seems like a red flag to me, as we should be preserving the include order that was specified by the project's `CMakeLists.txt`, but the differences in ordering could be caused by de-duplication of paths based on their presence in dependencies.
Looking for thoughts on that.
Even if the order in `CMakeLists.txt` is being respected somehow, alphabetizing the dependencies seems arbitrary. Maybe topological order would be better, but I still feel like …
=> Process direct ament dependencies in a deterministic order

.github/workflows/main.yml, ros2_example_bazel_installed/setup/prereq-rosdep-keys.txt
There are currently two issues breaking CI builds for this repository:
1. [Set LD_LIBRARY_PATH=/opt/drake/lib in CI builds](https://github.com/RobotLocomotion/drake-ros/commit/6dbce12c21d30811beca2f81db089e22bf4e9a4b)
Drake relies on RPATHs to locate dynamic libraries. ROS (and underlying Ubuntu libraries) do not use RPATHs when creating new dynamic binaries. Until recently, the Drake Docker images were setting LD_LIBRARY_PATH.
Unfortunately, relying on only RPATHs forces downstream consumers to either also rely on RPATHs for finding the upstream (Drake, in this case) libraries, or they need to make the upstream libraries discoverable dynamically. The easiset way to do this is to either use the LD_LIBRARY_PATH environment variable (as ROS does) or modify ld.so.conf.
This is a response to …
=> Multiple fixes for CI builds

.github/workflows/main.yml
Similar to #138 but for archive-based binaries for Focal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/145)
=> Add CI test against the ROS 2 Rolling archive for Focal

drake_ros_examples/examples/multirobot/multirobot.cc
Fixes multirobot build failure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/146)
=> get_graph_query_port -> get_graph_query_input_port

README.md
Otherwise, showed CI for all dev branches on upstream repo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/152)
=> README: Update CI badge to show only CI results for main

bazel_ros2_rules/ros2/resources/ros2bzl/templates.py, ros2_example_bazel_installed/BUILD.bazel, ros2_example_bazel_installed/WORKSPACE, ros2_example_bazel_installed/test/tf2_py_import_test.py
This should resolve a regression where C/C++ libraries were dropped from the file list for Python packages, resulting in import errors.
Regression caused by #150
Includes #178 to demonstrate the fix
Resolves #177
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/181)
=> Ensure C/C++ Python libraries are included in scraped packages

.github/workflows/main.yml, drake_ros_core/CMakeLists.txt, drake_ros_core/env-hooks/pydrake_pythonpath.sh.in, drake_ros_core/package.xml
~~This change borrows from the `PYTHONPATH` hook creation mechanism used in `ament_cmake_core`.~~
~~It makes the following assumptions:~~
~~1. Drake installs Python modules to `platlib`, and not `purelib`~~
~~2. Drake installs Python modules to the same prefix as `libdrake.so`~~
~~3. Drake uses the same Python interpreter version as the system's default~~
~~Closes #157~~
~~Related to #143~~
Requires RobotLocomotion/drake#18201
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/160)
=> Add Ament hook to put pydrake in PYTHONPATH

bazel_ros2_rules/ros2/resources/ros2bzl/scraping/system.py
This fixes a couple issues I noticed while debugging `bazel_ros2_rules` on Jammy. I'm not done debugging yet, but these two are easy ones I think can go in now.
The first is the regex looking for directoriers in the output of `ldconfig -XN --verbose` was not specific enough. It was matching warning messages and config files as if they were link directories. I fixed this by requiring `/` as the first character, and then checking that the directory actually exists.
The second issue is the output of `ld --verbose` included some search directories that don't exist. This doesn't seem to matter, but it adds extra stuff to look through when debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Only consider system directories that exist

bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in
This fixes one last issue when using the tarball from https://build.ros2.org/view/Hci/job/Hci__nightly-cyclonedds_ubuntu_jammy_amd64/
The same issue happens on [the ROS 2 buildfarm](https://build.ros2.org/job/Hbin_uJ64__rviz_rendering__ubuntu_jammy_amd64__binary/8/consoleText), but nothing is trying to use those targets so it's gone unnoticed. It went noticed here because the `bazel_ros2_rules` was trying to look for the libraries from those targets so that it could include them in the sandboxing. I'll also open a PR with a fix upstream.
This is the source of the console spam in Anzu.
EDIT: See https://github.com/ros2/rviz/pull/920 for discussion and root-cause analysis (most likely a breaking CMake change)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Workaround rviz_ogre_vendor not finding RenderSystem_GL.so

drake_ros_examples/examples/multirobot/multirobot.cc, drake_ros_examples/examples/multirobot/multirobot.py, drake_ros_tf2/test/test_tf_broadcaster.cc, drake_ros_tf2/test/test_tf_broadcaster.py
As of Drake PR ([#18106](https://github.com/RobotLocomotion/drake/pull/18106)), usage of `Publish` should be `ForcedPublish` As of now, `drake-ros` builds fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/190)
=> Use System.ForcedPublish in lieu of deprecated System.Publish

bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py, bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in, ros2_example_bazel_installed/BUILD.bazel, ros2_example_bazel_installed/WORKSPACE, ros2_example_bazel_installed/test/use_console_bridge.cc
The `@ros2//:console_bridge_vendor_cc` wasn't including any libraries to link on either Focal or Jammy. 
The first problem applies to both Focal and Jammy. The `bazel_ros2_rules` package assumes any found package will have CMake targets to link against, but the `console_bridge_vendor` doesn't have any. It expects users to `find_package(console_bridge)` and use that instead. This is fixed with a special case in the `ament_cmake_CMakeLists.txt` template to use `console_bridge` when `console_bridge_vendor` is requested.
The second problem applies only to`bazel_ros2_rules` on Jammy. The vendor package [uses the system package on Jammy because the version is new enough](https://github.com/ros2/console_bridge_vendor/blob/44389a5e8205fd3040c0ef8d0c452ac671786d09/CMakeLists.txt#L100-L105). …
=> Fix bazel_ros2_rules handling of console bridge

README.md, bazel_ros2_rules/README.md, bazel_ros2_rules/ros2/README.md
Per internal discussion.
Filed issue for RFC and possible symmetry:
- https://github.com/ApexAI/rules_ros/issues/5
- https://github.com/mvukov/rules_ros2/pull/24
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/194)
=> [doc] Add "Alternatives" for Bazel and ROS 2 workflows; mention ApexAI/rules_ros and mvukov/rules_ros2

drake_ros_tf2/.bazelrc, drake_ros_tf2/BUILD.bazel, drake_ros_tf2/CMakeLists.txt, drake_ros_tf2/WORKSPACE, drake_ros_tf2/test/test_tf_broadcaster.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/200)
=> Bazelize drake_ros_tf2

drake_ros_core/WORKSPACE, drake_ros_tf2/WORKSPACE, drake_ros_viz/WORKSPACE
Noticed in #189 
Bazel can no longer build the version of gtest specified by `drake_ros_core`, `drake_ros_viz`, and `drake_ros_tf2`. 
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/028206ac998ad78d07e8acc492e5bd46/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/runner/.cache/bazel/_bazel_runner/028206ac998ad78d07e8acc492e5bd46/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
INFO: Repository …
```
=> Upgrade gtest to fix breaking bazel change

drake_ros_core/package.xml
When building in an isolated workspace, CMake cannot find eigen3, as ``buildtool_export_depend`` tag is in the wrong place.
This fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/209)
=> Fix for eigen3 not found error in an isolated workspace

bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py
@EricCousineau-TRI Based on the slack conversation. The mistake can be seen in the error message shared in this StackOverflow post [here](https://stackoverflow.com/questions/75138403/pulling-ros2-packages-in-via-bazel-workspace-mech-in-drake-ros)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/213)
=> Fix minor ros2bzl error message spelling mistake

bazel_ros2_rules/ros2/defs.bzl
This PR addresses https://github.com/RobotLocomotion/drake-ros/issues/64 by stripping the trailing "/" characters from workspace strings.
Signed off by : aditya050995@gmail.com
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/211)
=> Strip "/" characters from workspace paths for ROS2

.github/workflows/main.yml
Start using official nightly archives which target Ubuntu Jammy in place of bespoke Focal tarballs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/206)
=> Switch to official Jammy tarballs in CI

.github/workflows/main.yml, drake_ros_core/src/publisher.cc, drake_ros_core/src/publisher.h, drake_ros_core/src/subscription.cc, drake_ros_core/src/subscription.h
APIs we're using changed in https://github.com/ros2/rclcpp/pull/2066 which is released in RCLCPP 18.0.0 in ROS ROlling. This PR uses the updated API.
Fixes #208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)
=> Update for Rolling PublisherBase and SubscriptionBase API change

.github/workflows/bazelized_drake_ros.yml
Oops per #252
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/254)
=> [ci] Hotfix to reenable Bazel drake_ros

drake_ros/core/drake_ros.h, drake_ros/core/geometry_conversions.h, drake_ros/core/publisher.h, drake_ros/core/ros_interface_system.h, drake_ros/core/ros_publisher_system.h, drake_ros/core/ros_subscriber_system.h, drake_ros/core/serializer_interface.h, drake_ros/core/subscription.h, drake_ros/tf2/name_conventions.h, drake_ros/tf2/scene_tf_broadcaster_system.h, drake_ros/tf2/scene_tf_system.h, drake_ros/viz/name_conventions.h, drake_ros/viz/rviz_visualizer.h, drake_ros/viz/scene_markers_system.h
I've tested this locally using this patch to Anzu, to prove that is fixes the build for me:
```patch
diff --git a/tools/workspace/ros2/drake_ros_repository.bzl b/tools/workspace/ros2/drake_ros_repository.bzl
index 8af666988..391e31116 100644
--- a/tools/workspace/ros2/drake_ros_repository.bzl
+++ b/tools/workspace/ros2/drake_ros_repository.bzl
@@ -18,6 +18,7 @@
def drake_ros_repository(name, mirrors = None):
github_archive(
name = name,
+        local_repository_override = "/home/jwnimmer/jwnimmer-tri/drake-ros",
repository = "RobotLocomotion/drake-ros",
extra_strip_prefix = "drake_ros",
commit = COMMIT,
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/263)
=> Add C++ namespace alises to smooth the transition

CONTRIBUTING.md, run_all_tests.sh
For at least the nominal settings of build options, CI should be a double-check, not a first-check; local testing should be trivial one-liner for contributors; and we should expect everyone to run the test suite locally before pushing to CI.
(To be clear -- using CI for canary builds like #245 is fine; the nominal build should be easy -- non-default options is OK to be more work.)
This is a first step towards enabling developers to quickly test their changes locally with confidence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/262)
=> Add helper script to run all tests locally

bazel_ros2_rules/README.md, drake_ros/core/drake_ros.cc, drake_ros/drake_ros/BUILD.bazel, drake_ros/drake_ros/CMakeLists.txt, drake_ros/drake_ros/core/__init__.py, drake_ros/drake_ros/core/cc_pybind.cc, drake_ros/drake_ros/drake_ros_pybind.h, drake_ros/drake_ros/test/core_test.py, drake_ros/drake_ros/test/test_pub_and_sub_cc_py.cc, ros2_example_bazel_installed/setup/prereq-rosdep-keys.txt
I would like to not get too creative when trying to bind C++ code that has `rclcpp::Node` arguments. This is one approach.
Relates https://github.com/ros2/rclpy/issues/291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/285)
=> [py] Make it easier to pass C++ node pointers in Python

Dockerfile, README.md, docker-README.md, docker-compose.yml
Targets #9
Ultimate aim is to be able to make `drake-ros` be accessible to all commonly used platforms for anyone to develop and try stuff out! 
Some notes about the approach, might be useful for the reviewers -
~- I use `npm` to install bazelisk as Drake's prereq installer doesn't yet support installing Bazel for non x86 platforms.~
- I allow users to be able to build from the latest drake master. I see the benefit to be two fold, obviously some users might want to try the latest and greatest features of drake asap and the second, is that M1 Mac/ARM Ubuntu users, including users of Nvidia Jetson platforms can now use `drake-ros` directly
- Building from source is currently a requirement for non x86 platforms. Hopefully once drake maintainers start hosting `aarch64` binaries, this won't …
=> Docker Containerization  

drake_ros_examples/examples/multirobot/multirobot.cc
As of now, currently the `multirobot` (cpp) version creates a 4x4 grid as compared to what it should be, a 5x5 one. The Python version works as expected. I have attached the videos which show the fewer robots + amputated kukas. 
Working Python version - 
https://github.com/RobotLocomotion/drake-ros/assets/38449494/7bab1543-740d-4146-9b44-b91d2e0db967
Broken Cpp version- 
https://github.com/RobotLocomotion/drake-ros/assets/38449494/f08671f0-83de-49b4-9d35-e33ffa8f963e
My guess is that `uint8_t` being compared with `size_t` seems to be the culprit. Although ideally it shouldn't, however, maybe it's some compiler settings that makes the treatment that ends up in this error?
cc: @EricCousineau-TRI for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> [fix] Multirobot cpp version doesn't create the correct plant setup and viz 

.gitignore, drake_ros_examples/examples/hydroelastic/CMakeLists.txt, drake_ros_examples/examples/hydroelastic/README.md, drake_ros_examples/examples/hydroelastic/launch/hydroelastic_cc_launch.py, drake_ros_examples/examples/iiwa_manipulator/CMakeLists.txt, drake_ros_examples/examples/iiwa_manipulator/README.md, drake_ros_examples/examples/iiwa_manipulator/launch/iiwa_manipulator_cc_launch.py, drake_ros_examples/examples/iiwa_manipulator/launch/iiwa_manipulator_py_launch.py, drake_ros_examples/examples/multirobot/CMakeLists.txt, drake_ros_examples/examples/multirobot/README.md, drake_ros_examples/examples/multirobot/launch/multirobot_cc_launch.py, drake_ros_examples/examples/multirobot/launch/multirobot_py_launch.py
This PR adds launch files to all the examples that involve a visual (`rviz`) component. All the launch files were tested.
@EricCousineau-TRI for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/289)
=> Add ROS2 Launch Files to all relevant examples 

drake_ros/drake.bzl
Closes #296.
See also #293.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/294)
=> Upgrade Drake to latest release 1.20.0

.github/workflows/bazelized.yml, .github/workflows/bazelized_drake_ros.yml
Fixes CI due to ubuntu version mismatch. Old libs require a restart after an upgrade which makes the CI jobs fail.
``bazelized.yaml`` uses ``ubuntu-latest`` and ``bazelized_drake_ros.yaml`` uses ``ubuntu-22.04`` which probably point to different versions now. This PR makes the versions consistent, using latest on both. I'd personally prefer specifying the exact version of ubuntu to be used, but I'm open for suggestions.
EDIT : Use ubuntu-22.04 in both CI jobs, and remove ``needrestart``
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301)
=> Update ubuntu version in bazelized_drake_ros.yml

bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py
CMake fails for many packages in the default ros2 humble install, leaving expected cmake api query results empty. This handles the failure and surfaces the name of the failing package for investigation.
In order to artificially generate errors, leave `include_packages` empty in a `ros2_local_repository` instance to pull in all installed packages. Many will have cmake failures.
To see the specific errors I encountered, apply the following change to the `//ros2_example_bazel_installed:WORKSPACE`  and run `bazel build //...` from `ros2_example_bazel_installed`
```
ros2_local_repository(
name = "ros2" if ROS2_DISTRO_PREFIX else "ros2_ignored",
-    include_packages = ROS2_PACKAGES,
+    # include_packages = ROS2_PACKAGES,
workspaces = [ROS2_DISTRO_PREFIX],
)
```
- - -
This change is [<img …
=> Handle cmake failures in dependent packages

bazel_ros2_rules/ros2/rosidl.bzl, bazel_ros2_rules/ros2/tools/dload.bzl, ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel
Towards Anzu bugfix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/305)
=> [rosidl] Ensure *_defs data is added to *_py and *_cc targets

.github/workflows/bazelized_drake_ros.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/306)
=> [ci] Always save cache, even on failure

.github/runner_free_space.sh, .github/workflows/bazelized_drake_ros.yml, drake_ros_examples/setup/install_prereqs.sh
Towards #247
EDIT: Currently shown at the start:
```sh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   61G   23G  74% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  31% /mnt
tmpfs           693M   12K  693M   1% /run/user/1001
```
After build + test + clean of `drake_ros`, then install prereqs of `drake_ros_examples`:
```sh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   74G  9.3G  89% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.2M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi …
```
=> [ci] Free up disk space on GitHub CI runner

bazel_ros2_rules/setup/install_prereqs.sh, drake_ros/drake.bzl, ros2_example_bazel_installed/setup/install_prereqs.sh
Resolves #318
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/319)
=> [drake] Upgrade to v1.23.0

ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel
Missing `rmw_implementation` in `simple_talker.py`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/320)
=> Added missing rmw_implementation to simple_talker

drake_ros_examples/examples/hydroelastic/hydroelastic.cc, drake_ros_examples/examples/multirobot/multirobot.cc
When I was developing this PR https://github.com/RobotLocomotion/drake-ros/pull/323 I found some issues with the deprecation of `AddModelFromFile`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/326)
=> Replaced AddModelFromFile with AddModels

drake_ros/drake.bzl, drake_ros/drake_ros/core/cc_pybind.cc
Upgrades drake version and adds a bugfix : hold the GIL in PyserializerInterface. cc @ahcorde 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/334)
=> Upgrade to drake 1.26

.github/workflows/main.yml, README.md, drake_ros/CMakeLists.txt, drake_ros_examples/CMakeLists.txt
Rolling is moving to Ubuntu Noble, and won't be releasing new packages on Jammy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/338)
=> Disable rolling CI

.lint/.bazeliskrc, bazel_ros2_rules/.bazeliskrc, drake_ros/.bazeliskrc, drake_ros_examples/.bazeliskrc, ros2_example_bazel_installed/.bazeliskrc
Needed to incorporate this to keep expectations for my dev machine as I was hacking towards #298
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/343)
=> Add bazelisk files

.lint/.bazeliskrc, .lint/.bazelrc, bazel_ros2_rules/.bazeliskrc, bazel_ros2_rules/setup/install_prereqs.sh, default.bazelrc, drake_ros/.bazeliskrc, drake_ros_examples/.bazeliskrc, ros2_example_bazel_installed/.bazeliskrc, ros2_example_bazel_installed/setup/install_prereqs.sh, ros2_example_bazel_installed/tools/environ.bzl
To match Anzu
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/349)
=> [bazelisk] Use Bazel 7.1.2

.github/workflows/bazelized_drake_ros.yml, drake_ros/drake.bzl
Closes #351.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/352)
=> Upgrade to Drake 1.29

drake_ros/CMakeLists.txt, drake_ros_examples/CMakeLists.txt
In no universe should Werror be enabled in end-user builds (rather than just developers local builds and CI checks), and certainly not for warning categories that Drake's own CI doesn't even enable. We don't want *this* repository to be a warning-catcher for Drake code.
The easy fix for now is to just turn off the overly broad warning categories. This does not fix the bug that Werror=all is enabled for builds triggered by downstream users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/360)
=> [cmake] Turn off -Werror=extra -Werror=pedantic

drake_ros/CMakeLists.txt, drake_ros/drake.bzl, drake_ros/drake_ros/CMakeLists.txt, drake_ros/viz/scene_markers_system.cc, ros2_example_bazel_installed/setup/prereq-rosdep-keys.txt
Closes #367.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/368)
=> Upgrade to Drake 1.34.0

bazel_ros2_rules/ros2/resources/templates/package_cc_library.bazel.tpl, bazel_ros2_rules/ros2/resources/templates/package_py_library.bazel.tpl, bazel_ros2_rules/ros2/resources/templates/package_py_library_with_cc_libs.bazel.tpl, bazel_ros2_rules/ros2/tools/common.bzl
See https://github.com/bazelbuild/bazel/issues/8195.
I ran an Anzu full local build+test against this patch (still with Bazel 7) and everything passed.
I didn't check that all of these were strictly necessary, I just blindly added the flag in places where it seemed conceivable to fail.
+@EricCousineau-TRI for stamping, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/375)
=> Fix --incompatible_disallow_empty_glob=true for Bazel 8

drake_ros/core/ros_publisher_system.cc, drake_ros/core/ros_publisher_system.h, drake_ros/core/ros_subscriber_system.cc, drake_ros/core/ros_subscriber_system.h, drake_ros/drake_ros/core/cc_pybind.cc
Towards https://github.com/RobotLocomotion/drake/issues/21968.
This contains the same kind of fixes as https://github.com/RobotLocomotion/drake/pull/19369 and https://github.com/RobotLocomotion/drake/pull/22463, plus one additional change (removing the apparently unnecessary `py::wrapper`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/374)
=> Switch pub/sub serializers away from unique_ptr

.lint/.bazeliskrc, bazel_ros2_rules/.bazeliskrc, bazel_ros2_rules/setup/install_prereqs.sh, default.bazelrc, drake_ros/.bazeliskrc, drake_ros/drake.bzl, drake_ros/drake_ros/core/cc_pybind.cc, drake_ros_examples/.bazeliskrc, drake_ros_examples/examples/multirobot/multirobot.cc, drake_ros_examples/examples/multirobot/multirobot.py, ros2_example_bazel_installed/.bazeliskrc, ros2_example_bazel_installed/README.md, ros2_example_bazel_installed/setup/install_prereqs.sh
Toward https://github.com/RobotLocomotion/drake-ros/issues/373 and https://github.com/RobotLocomotion/drake-ros/issues/376.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/377)
=> Upgrade to Drake suggested 1.37.0

.github/runner_free_space.sh, bazel_ros2_rules/ros2/README.md, bazel_ros2_rules/ros2/defs.bzl, bazel_ros2_rules/ros2/generate_build_file.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_python.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/metadata.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/python.py, bazel_ros2_rules/ros2/resources/ros2bzl/templates.py, ros2_example_bazel_installed/WORKSPACE, ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel
Closes #382. Built on top of #381. Precisely what the title says, handling ROS packages that install Python packages with different names and no hint to the relationship between them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/383)
=> Add pure Python package scraping

.github/workflows/main.yml, drake_ros/.bazelrc, drake_ros/drake.bzl, drake_ros/drake_ros/core/cc_pybind.cc, drake_ros_examples/.bazelrc, fix_bazel_lint.sh
Closes https://github.com/RobotLocomotion/drake-ros/issues/380. Drops the dependency on Drake's `pybind` fork in the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/387)
=> Migrate from Drake 1.37 to Drake 1.40

bazel_ros2_rules/ros2/resources/cmake_tools/file_api.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/metadata.py, bazel_ros2_rules/ros2/resources/ros2bzl/scraping/python.py, bazel_ros2_rules/ros2/resources/templates/package_cc_library.bazel.tpl
Hello drake-ros maintainers,
Thank you for making this project available. We have been using it to build our software for the past months and we have built up a number of patches that we hope can be useful to everyone.
This PR is the first I'm opening and it contains 4 small patches related to various edge cases in the workspace scrapping that we have encountered.
Below is a short summary of the individual patches, I am happy to submit separate PRs if you prefer.
P1: Remove elements that have a condition attribute on ROS1
This is used by a number of packages that are trying to support both versions at the same time.
This patch is actually part of https://github.com/RobotLocomotion/drake-ros/pull/336 we actually had our own patch that does pretty much the same thing (including packages …
=> Miscellaneous scrapping fixes
