RobotLocomotion/drake-ros

- drake_ros_core/CMakeLists.txt
- drake_ros_core/README.md
- drake_ros_core/include/drake_ros_core/drake_ros.hpp
- drake_ros_core/include/drake_ros_core/drake_ros_interface.hpp
- drake_ros_core/include/drake_ros_core/ros_interface_system.hpp
- drake_ros_core/include/drake_ros_core/ros_publisher_system.hpp
- drake_ros_core/include/drake_ros_core/ros_subscriber_system.hpp
- drake_ros_core/include/drake_ros_core/serializer.hpp
- drake_ros_core/include/drake_ros_core/serializer_interface.hpp
- drake_ros_core/package.xml
- drake_ros_core/src/drake_ros.cpp
- drake_ros_core/src/publisher.cpp
- drake_ros_core/src/publisher.hpp
- drake_ros_core/src/ros_interface_system.cpp
- drake_ros_core/src/ros_publisher_system.cpp
- drake_ros_core/src/ros_subscriber_system.cpp
- drake_ros_core/src/subscription.cpp
- drake_ros_core/src/subscription.hpp
- drake_ros_core/test/test_drake_ros.cpp
- drake_ros_core/test/test_pub_sub.cpp
Spin off from #2. Includes Drake C++ systems for publishing and subscribing to ROS2 messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/5)
> Add drake_ros_core package.

- drake_ros_core/src/ros_subscriber_system.cpp
Follow up to https://github.com/RobotLocomotion/drake-ros/pull/11/files#r690758458
Mimics https://github.com/RobotLocomotion/drake/pull/15563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/12)
> Use DeclareStateOutputPort instead of DeclareAbstractOutputPort

- .github/workflows/main.yml
- README.md
Closes #26. Should be rebase-merged, not squashed-merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/28)
> Update drake-ros CI workflow 

- README.md
Closes #8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/30)
> Link style guide in root README.md

- drake_ros_tf2/CMakeLists.txt
- drake_ros_tf2/src/scene_tf_system.cc
- drake_ros_tf2/src/utilities/internal_name_conventions.h
- drake_ros_tf2/src/utilities/name_conventions.cc
- drake_ros_tf2/test/test_name_conventions.cc
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
Addresses comments in https://github.com/RobotLocomotion/drake-ros/pull/20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/35)
> Addressing comments

- drake_ros_tf2/.clang-format
- drake_ros_tf2/CMakeLists.txt
- drake_ros_tf2/CPPLINT.cfg
- drake_ros_tf2/README.md
- drake_ros_tf2/include/drake_ros_tf2/scene_tf_broadcaster_system.h
- drake_ros_tf2/include/drake_ros_tf2/scene_tf_system.h
- drake_ros_tf2/include/drake_ros_tf2/utilities/name_conventions.h
- drake_ros_tf2/include/drake_ros_tf2/utilities/type_conversion.h
- drake_ros_tf2/package.xml
- drake_ros_tf2/src/scene_tf_broadcaster_system.cc
- drake_ros_tf2/src/scene_tf_system.cc
- drake_ros_tf2/src/utilities/internal_name_conventions.h
- drake_ros_tf2/src/utilities/name_conventions.cc
- drake_ros_tf2/src/utilities/type_conversion.cc
- drake_ros_tf2/test/test_name_conventions.cc
- drake_ros_tf2/test/test_tf_broadcaster.cc
- drake_ros_tf2/test/test_type_conversion.cc
Spin off from #2. Built on top of #6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/20)
> Add drake_ros_tf2 package

- bazel_ros2_rules/ros2/defs.bzl
Fixes #53 thats to @hidmic's comment https://github.com/RobotLocomotion/drake-ros/issues/53#issuecomment-1088740125
@IanTheEngineer & @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/54)
> Use --output so ROS_DISTRO being set doesn't affect build

- README.md
While the `develop` branch is not stable, it would be useful for external
visitors to have us point to it in the `main` README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/58)
> Update README to reflect development status

- bazel_ros2_rules/setup/install_prereqs.sh
- ros2_example_bazel_installed/setup/install_prereqs.sh
In parallel w/ Anzu PR 8708, Drake PR https://github.com/RobotLocomotion/drake/pull/16878
\cc @IanTheEngineer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/62)
> setup: Use Bazel 5.1.0

- drake_ros_core/package.xml
- drake_ros_viz/CMakeLists.txt
- drake_ros_viz/include/drake_ros_viz/rviz_visualizer.h
- drake_ros_viz/include/drake_ros_viz/scene_markers_system.h
- drake_ros_viz/package.xml
- drake_ros_viz/src/rviz_visualizer.cc
- drake_ros_viz/src/scene_markers_system.cc
- drake_ros_viz/test/test_scene_markers.cc
Spin off form #2. Built on top of #22.
To do:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/23)
> Add Drake C++ systems to drake_ros_viz package.

- bazel_ros2_rules/ros2/resources/rmw_isolation/rmw_isolation.py
- bazel_ros2_rules/ros2/resources/ros2bzl/resources.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_python.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/system.py
- bazel_ros2_rules/ros2/resources/ros2bzl/templates.py
- bazel_ros2_rules/ros2/resources/ros2bzl/utilities.py
Remove unused function
While reviewing comment in #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/97)
> Minor code formatting changes

- ros2_example_bazel_installed/WORKSPACE
To help investigate w/ #99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/101)
> Add ros2cli and common extensions to bazel workspace

- ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel
- ros2_example_bazel_installed/ros2_example_apps/simple_talker.py
- ros2_example_bazel_installed/ros2_example_apps/test/custom_message_echo_test.py
Towards #118
\cc @cottsay 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/119)
> ros2: Add test showing how to echo custom messages

- .github/workflows/main.yml
Closes #131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/138)
> Add Rolling and Humble CI jobs for debians

- .github/workflows/main.yml
- drake_ros_core/CMakeLists.txt
- drake_ros_core/env-hooks/drake_library_path.sh.in
Closes #139
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/143)
> Add Ament hook to put libdrake.so in LD_LIBRARY_PATH

- drake_ros_examples/examples/multirobot/multirobot.py
Like #146 but for Python
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/147)
> [Python] get_graph_query_port -> get_graph_query_input_port

- CONTRIBUTING.md
- README.md
Carved from #170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/179)
> README: Fix typo. Separate CONTRIBUTING doc

- ros2_example_bazel_installed/WORKSPACE
From #178
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/180)
> WORKSPACE: Separate out RMW implementation

- drake_ros_core/BUILD.bazel
- drake_ros_core/CMakeLists.txt
- drake_ros_core/include/drake_ros_core/drake_ros_core_pybind.h
- drake_ros_core/include/drake_ros_core/qos_pybind.h
- drake_ros_core/include/drake_ros_core/serializer_interface_pybind.h
- drake_ros_core/src/module_py.cc
- drake_ros_tf2/CMakeLists.txt
- drake_ros_tf2/include/drake_ros_tf2/drake_ros_tf2_pybind.h
- drake_ros_tf2/src/module_py.cc
- drake_ros_viz/CMakeLists.txt
- drake_ros_viz/include/drake_ros_viz/drake_ros_viz_pybind.h
- drake_ros_viz/src/module_py.cc
Resolves #168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/171)
> Follow Drake Python binding conventions more closely

- fix_ament_lint.sh
While working on #175, #171. Found it painful to try and reason about how to reformat error messages into fixes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/176)
> Add fix_ament_lint script

- drake_ros_core/CMakeLists.txt
- drake_ros_examples/CMakeLists.txt
- drake_ros_tf2/CMakeLists.txt
- drake_ros_viz/CMakeLists.txt
Relates to #190 and the conversation with Jeremy on Slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/191)
> [cmake] Ensure that deprecations are not errors

- drake_ros_core/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/198)
> Use Drake v1.10.0

- drake_ros_viz/.bazelrc
- drake_ros_viz/BUILD.bazel
- drake_ros_viz/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/202)
> Bazelize drake_ros_viz

- README.md
attempts to solve #218
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/220)
> Reflects supported ROS + Linux combinations

- .github/workflows/bazelized.yml
- .github/workflows/bazelized_drake_ros.yml
- .github/workflows/drake_model_interop.yml
Resolves #222
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/223)
> [ci] Ensure workflows run against updates to `main` and `develop`

- .github/workflows/drake_model_interop.yml
Hotfix to #223
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/225)
> [ci] Revert workflow change to drake_model_interop repo

- .github/ci.bazelrc
- .github/workflows/bazelized.yml
- .github/workflows/bazelized_drake_ros.yml
- .gitignore
- bazel_ros2_rules/.bazelrc
- drake_ros_core/.bazelrc
- drake_ros_tf2/.bazelrc
- drake_ros_viz/.bazelrc
- ros2_example_bazel_installed/.bazelrc
Towards more visibility for #221
Reflects Drake's configuration:
https://github.com/RobotLocomotion/drake/blob/v1.13.0/tools/bazel.rc#L17-L19
as well as
https://github.com/RobotLocomotion/drake-ci/blob/0f2c21584f017a5482ce03e04b8aaceb952746a9/user.bazelrc#L42
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/226)
> [bazel, ci] Use settings similar to Drake's for testing 

- .github/workflows/bazelized.yml
Resolves #221
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/227)
> [ci] Ensure we can use lldb on Docker for GitHub actions

- .github/workflows/bazelized.yml
- .github/workflows/bazelized_drake_ros.yml
- .github/workflows/drake_model_interop.yml
- .github/workflows/main.yml
- CONTRIBUTING.md
Using while prototyping things such #169
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/170)
> [ci] Allow disabling CI via PR label

- bazel_ros2_rules/ros2/generate_distro_file.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py
- bazel_ros2_rules/ros2/resources/templates/distro.bzl.tpl
Resolves https://github.com/RobotLocomotion/drake-ros/issues/111, by exporting a default value for ``ROS_DISTRO``.
Signed-off-by: Aditya Pande <aditya.pande@openrobotics.org>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/217)
> Export ``ROS_DISTRO`` environment variable

- CONTRIBUTING.md
- README.md
- bazel_ros2_rules/ros2/resources/rmw_isolation/package.BUILD.bazel
- drake_ros/README.md
- drake_ros/tf2/README.md
- drake_ros/viz/README.md
- drake_ros_examples/README.md
- drake_ros_examples/examples/iiwa_manipulator/CMakeLists.txt
- drake_ros_examples/examples/iiwa_manipulator/README.md
- drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py
- drake_ros_examples/examples/multirobot/README.md
- drake_ros_examples/examples/multirobot/multirobot.cc
- drake_ros_examples/examples/multirobot/multirobot.py
- drake_ros_examples/examples/rs_flip_flop/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/235)
> [drake_ros_example] Add Getting Started indicator

- .lint/WORKSPACE
- .lint/drake.bzl
- drake_ros/drake.bzl
- drake_ros/viz/test/test_python_bindings.py
lint: Use symlink drake.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/242)
> Bump to use Drake v1.13.0

- .github/ci.bazelrc
- .github/workflows/bazelized.yml
- .github/workflows/bazelized_drake_ros.yml
Resolves #247
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/248)
> [ci] Narrow bazel cache to repository and disk cache

- drake_ros/core/test/test_drake_ros.cc
Towards #233.
+@EricCousineau-TRI for review, please.
\CC @sloretz FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/250)
> [drake_ros] Add regression test for C++ shimming

- drake_ros/BUILD.bazel
- drake_ros/core/BUILD.bazel
- drake_ros/drake_ros/BUILD.bazel
- drake_ros/drake_ros/cc_py.cc
- drake_ros/drake_ros/core/cc_pybind.cc
- drake_ros/drake_ros/drake_ros_pybind.h
- drake_ros/drake_ros/test/odr_py_test.py
- drake_ros/drake_ros/tf2/cc_pybind.cc
- drake_ros/drake_ros/viz/cc_pybind.cc
- drake_ros/tf2/BUILD.bazel
- drake_ros/tools/BUILD.bazel
- drake_ros/tools/skylark/BUILD.bazel
- drake_ros/tools/skylark/drake_ros_cc.bzl
- drake_ros/tools/skylark/extract_cc.bzl
- drake_ros/viz/BUILD.bazel
Resolves #151
Requires #238
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/239)
> [py] Avoid ODR violations in bindings

- drake_ros_examples/BUILD.bazel
- drake_ros_examples/WORKSPACE
- drake_ros_examples/examples/iiwa_manipulator/BUILD.bazel
- drake_ros_examples/examples/iiwa_manipulator/CMakeLists.txt
- drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.cpp
- drake_ros_examples/examples/iiwa_manipulator/iiwa_manipulator.py
- drake_ros_examples/examples/iiwa_manipulator/test/iiwa_manipulator_test.py
- drake_ros_examples/examples/multirobot/BUILD.bazel
- drake_ros_examples/examples/multirobot/multirobot.cc
- drake_ros_examples/examples/multirobot/multirobot.py
- drake_ros_examples/examples/rs_flip_flop/BUILD.bazel
- drake_ros_examples/examples/rs_flip_flop/CMakeLists.txt
- drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.cpp
- drake_ros_examples/examples/rs_flip_flop/rs_flip_flop.py
- drake_ros_examples/examples/rs_flip_flop/test/rs_flip_flop_test.py
- drake_ros_examples/test/bazel_ros_testing.py
- drake_ros_examples/test/drake_ros_py_import_test.py
Resolves #251
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/255)
> [drake_ros_examples] Ensure Bazel build passes

- bazel_ros2_rules/ros2/ros_cc.bzl
Partially reverts #233.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/261)
> [bazel_ros2_rules] Revert ros_cc_test feature for shim control

- drake_ros_examples/README.md
\cc @adeeb10abbas I think this would help w/ `colcon` and `rosdep`?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/264)
> [setup] Add instructions for installing dev tools

- README.md
Based on my conversation w/ @EricCousineau-TRI 
Reflects the current state of drake-ros. Removes misleading, outdated language.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/267)
> [minor] Removes outdated text for paused subproject

- .github/workflows/bazelized.yml
- bazel_ros2_rules/ros2/BUILD.bazel
- bazel_ros2_rules/ros2/plugin_xml_parsing_test.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py
- bazel_ros2_rules/ros2/resources/ros2bzl/scraping/metadata.py
- run_all_tests.sh
Fixes #266
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/268)
> Fix plugin xml parsing with multiple library tags

- .github/workflows/main.yml
- drake_ros/CMakeLists.txt
- drake_ros/core/CMakeLists.txt
- drake_ros/core/subscription.cc
- drake_ros/core/subscription.h
- drake_ros/tf2/CMakeLists.txt
- drake_ros/viz/CMakeLists.txt
This is a temp PR meant to clean up CI. Resolves https://github.com/RobotLocomotion/drake-ros/issues/274
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/275)
> Fastcdr CI cleanup, ros rolling API changes

- drake_ros/core/ros_publisher_system.cc
- drake_ros/core/ros_subscriber_system.cc
See https://github.com/RobotLocomotion/drake/pull/19989.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/292)
> [drake_ros] Use modern drake::systems::Event API

- .github/ci.bazelrc
- .github/workflows/bazelized.yml
- .github/workflows/bazelized_drake_ros.yml
Using suggestions from #247 / drake-blender
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/295)
> [ci] Update github caching to be more similar to drake-blender

- drake_ros/drake.bzl
Closes https://github.com/RobotLocomotion/drake-ros/issues/299.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/304)
> Upgrade Drake to release 1.22.0

- bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in
Resolves #315
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/316)
> [cmake] Workaround rosbag2_storage_mcap package issues

- drake_ros/core/CMakeLists.txt
- drake_ros/core/test/test_clock_system.cc
Included clock system test in CMake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/324)
> Included clock system test in CMake

- drake_ros_examples/examples/multirobot/multirobot.py
Related with this PR https://github.com/RobotLocomotion/drake-ros/pull/328 
CI is failing https://github.com/RobotLocomotion/drake-ros/actions/runs/7628442386/job/20779511766?pr=328
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/329)
> Fixed deprecation: multirobot.py

- drake_ros/drake.bzl
Closes #327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/328)
> [drake] Upgrade to v1.25.0

- default.bazelrc
Use C++ 20 in bazelrc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/341)
> Move to C++ 20

- drake_ros/viz/scene_markers_system.cc
This is required as of the latest Drake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/357)
> Add a missing semicolon

- .github/workflows/bazelized_drake_ros.yml
Resolves #361
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/363)
> [ci] Stop using ros-tooling/setup-ros

- drake_ros/drake.bzl
Resolves #362
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/364)
> Upgrade to Drake 1.31

- drake_ros/drake.bzl
Resolves #365
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-ros/366)
> Upgrade to Drake 1.32
